"""initial migration

Revision ID: 0a3b6a5059ad
Revises: 
Create Date: 2023-10-10 18:21:29.211692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a3b6a5059ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request',
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.String(length=256), nullable=False),
    sa.Column('blinded_utxo', sa.String(length=256), nullable=False),
    sa.Column('asset_group', sa.String(length=256), nullable=False),
    sa.Column('asset_id', sa.String(length=256), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('idx')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request')
    # ### end Alembic commands ###
