"""recipient_id and invoice

Revision ID: e5a50dcb84c2
Revises: 0a3b6a5059ad
Create Date: 2023-10-11 10:56:32.689002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5a50dcb84c2'
down_revision = '0a3b6a5059ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.alter_column('blinded_utxo', new_column_name='recipient_id')
        batch_op.add_column(sa.Column('invoice', sa.String(length=256), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.alter_column('recipient_id', new_column_name='blinded_utxo')
        batch_op.drop_column('invoice')

    # ### end Alembic commands ###
